-- firniss.phone : données de départ (généré depuis src/lib/catalog.ts). Prix d'exemple en euros.

insert into products (id, name, generation, is_pro, condition, camera, has_island, is_new, colors, storage, stock, active, sort) values
  ('iphone-18-pro-max', 'iPhone 18 Pro Max', 18, true, 'neuf', 'plateau', true, true, '[{"name":"Bordeaux","hex":"#6b1e2e","image":null},{"name":"Bleu nuit","hex":"#1f2d4d","image":null},{"name":"Argent","hex":"#cfd2d6","image":null}]'::jsonb, '[{"go":256,"price":1479},{"go":512,"price":1709},{"go":1024,"price":1939}]'::jsonb, 5, true, 0),
  ('iphone-18-pro', 'iPhone 18 Pro', 18, true, 'neuf', 'plateau', true, true, '[{"name":"Bleu nuit","hex":"#1f2d4d","image":null},{"name":"Bordeaux","hex":"#6b1e2e","image":null},{"name":"Argent","hex":"#cfd2d6","image":null}]'::jsonb, '[{"go":256,"price":1329},{"go":512,"price":1559},{"go":1024,"price":1789}]'::jsonb, 5, true, 1),
  ('iphone-17-pro-max', 'iPhone 17 Pro Max', 17, true, 'neuf', 'plateau', true, false, '[{"name":"Orange cosmique","hex":"#f07a24","image":null},{"name":"Bleu intense","hex":"#2f3c5a","image":null},{"name":"Argent","hex":"#d7d9dc","image":null}]'::jsonb, '[{"go":256,"price":1249},{"go":512,"price":1479},{"go":1024,"price":1709}]'::jsonb, 5, true, 2),
  ('iphone-17', 'iPhone 17', 17, false, 'neuf', 'duo', true, false, '[{"name":"Noir","hex":"#2a2a2e","image":null},{"name":"Blanc","hex":"#eeeeec","image":null},{"name":"Bleu brume","hex":"#9fb7d1","image":null},{"name":"Lavande","hex":"#cdbbe6","image":null},{"name":"Sauge","hex":"#b9c9ad","image":null}]'::jsonb, '[{"go":256,"price":879},{"go":512,"price":1109}]'::jsonb, 5, true, 3),
  ('iphone-16-pro-max', 'iPhone 16 Pro Max', 16, true, 'recond', 'trio', true, false, '[{"name":"Titane noir","hex":"#3a3a3c","image":null},{"name":"Titane blanc","hex":"#e6e4df","image":null},{"name":"Titane naturel","hex":"#b6b0a6","image":null},{"name":"Titane désert","hex":"#bfa48f","image":null}]'::jsonb, '[{"go":256,"price":949},{"go":512,"price":1169},{"go":1024,"price":1399}]'::jsonb, 5, true, 4),
  ('iphone-16', 'iPhone 16', 16, false, 'recond', 'duo', true, false, '[{"name":"Noir","hex":"#2c2c2e","image":null},{"name":"Blanc","hex":"#f0f0ee","image":null},{"name":"Rose","hex":"#f0a3d4","image":null},{"name":"Sarcelle","hex":"#9ccfcb","image":null},{"name":"Outremer","hex":"#7d8fe0","image":null}]'::jsonb, '[{"go":128,"price":649},{"go":256,"price":759},{"go":512,"price":979}]'::jsonb, 5, true, 5),
  ('iphone-15-pro', 'iPhone 15 Pro', 15, true, 'recond', 'trio', true, false, '[{"name":"Titane naturel","hex":"#bab4aa","image":null},{"name":"Titane bleu","hex":"#3d4555","image":null},{"name":"Titane blanc","hex":"#e3e1dc","image":null},{"name":"Titane noir","hex":"#3b3b3d","image":null}]'::jsonb, '[{"go":128,"price":699},{"go":256,"price":809},{"go":512,"price":1029}]'::jsonb, 5, true, 6),
  ('iphone-15', 'iPhone 15', 15, false, 'recond', 'diag', true, false, '[{"name":"Noir","hex":"#35383b","image":null},{"name":"Bleu","hex":"#c9dde6","image":null},{"name":"Vert","hex":"#d5e2c8","image":null},{"name":"Jaune","hex":"#f3e7a6","image":null},{"name":"Rose","hex":"#f0cdd3","image":null}]'::jsonb, '[{"go":128,"price":529},{"go":256,"price":639},{"go":512,"price":859}]'::jsonb, 5, true, 7),
  ('iphone-14-pro-max', 'iPhone 14 Pro Max', 14, true, 'recond', 'trio', true, false, '[{"name":"Violet intense","hex":"#594f63","image":null},{"name":"Or","hex":"#ecdcc0","image":null},{"name":"Argent","hex":"#e3e4e5","image":null},{"name":"Noir sidéral","hex":"#3b3a3c","image":null}]'::jsonb, '[{"go":128,"price":589},{"go":256,"price":699},{"go":512,"price":919}]'::jsonb, 5, true, 8),
  ('iphone-14', 'iPhone 14', 14, false, 'recond', 'diag', false, false, '[{"name":"Minuit","hex":"#2b3038","image":null},{"name":"Lumière stellaire","hex":"#f2ece3","image":null},{"name":"(PRODUCT)RED","hex":"#c8102e","image":null},{"name":"Bleu","hex":"#a9bfd4","image":null},{"name":"Violet","hex":"#d5c5e3","image":null},{"name":"Jaune","hex":"#f4e28d","image":null}]'::jsonb, '[{"go":128,"price":419},{"go":256,"price":529},{"go":512,"price":749}]'::jsonb, 5, true, 9),
  ('iphone-13-pro', 'iPhone 13 Pro', 13, true, 'recond', 'trio', false, false, '[{"name":"Graphite","hex":"#4a4a4c","image":null},{"name":"Or","hex":"#f0dfc2","image":null},{"name":"Argent","hex":"#e4e5e3","image":null},{"name":"Bleu alpin","hex":"#a7c1d9","image":null},{"name":"Vert alpin","hex":"#576856","image":null}]'::jsonb, '[{"go":128,"price":459},{"go":256,"price":569},{"go":512,"price":789}]'::jsonb, 5, true, 10),
  ('iphone-13', 'iPhone 13', 13, false, 'recond', 'diag', false, false, '[{"name":"Minuit","hex":"#2b3038","image":null},{"name":"Lumière stellaire","hex":"#f2ece3","image":null},{"name":"(PRODUCT)RED","hex":"#c8102e","image":null},{"name":"Bleu","hex":"#2f5874","image":null},{"name":"Rose","hex":"#f5d3d6","image":null},{"name":"Vert","hex":"#44574a","image":null}]'::jsonb, '[{"go":128,"price":349},{"go":256,"price":459},{"go":512,"price":679}]'::jsonb, 5, true, 11),
  ('iphone-12', 'iPhone 12', 12, false, 'recond', 'duo', false, false, '[{"name":"Noir","hex":"#25262a","image":null},{"name":"Blanc","hex":"#f4f4f2","image":null},{"name":"(PRODUCT)RED","hex":"#c8102e","image":null},{"name":"Vert","hex":"#cfe6d3","image":null},{"name":"Bleu","hex":"#2b4a7a","image":null},{"name":"Violet","hex":"#b7a9d2","image":null}]'::jsonb, '[{"go":64,"price":269},{"go":128,"price":299},{"go":256,"price":369}]'::jsonb, 5, true, 12),
  ('iphone-11', 'iPhone 11', 11, false, 'recond', 'duo', false, false, '[{"name":"Violet","hex":"#c9b8e8","image":null},{"name":"Jaune","hex":"#f9e79a","image":null},{"name":"Vert","hex":"#b9e2cf","image":null},{"name":"Noir","hex":"#27272a","image":null},{"name":"Blanc","hex":"#f4f4f2","image":null},{"name":"(PRODUCT)RED","hex":"#c8102e","image":null}]'::jsonb, '[{"go":64,"price":199},{"go":128,"price":229},{"go":256,"price":289}]'::jsonb, 5, true, 13)
on conflict (id) do nothing;

insert into payment_methods (code, name, country, instructions, active, sort) values
  ('wafacash', 'Wafacash', 'MA', 'Envoyez le montant par Wafacash au nom de [VOTRE NOM], puis envoyez-nous le code de transfert par WhatsApp.', true, 0),
  ('banque-populaire', 'Banque Populaire', 'MA', 'Faites un virement vers le RIB [VOTRE RIB BANQUE POPULAIRE], puis envoyez-nous le reçu par WhatsApp.', true, 1),
  ('cih', 'CIH Bank', 'MA', 'Faites un virement vers le RIB [VOTRE RIB CIH], puis envoyez-nous le reçu par WhatsApp.', true, 2),
  ('airtel-money', 'Airtel Money', 'GA', 'Envoyez le montant par Airtel Money au [VOTRE NUMÉRO AIRTEL], puis envoyez-nous la capture de la transaction par WhatsApp.', true, 3),
  ('moov-money', 'Moov Money', 'GA', 'Envoyez le montant par Moov Money au [VOTRE NUMÉRO MOOV], puis envoyez-nous la capture de la transaction par WhatsApp.', true, 4),
  ('wave', 'Wave', 'GA', 'Envoyez le montant par Wave au [VOTRE NUMÉRO WAVE], puis envoyez-nous la capture de la transaction par WhatsApp.', true, 5)
on conflict (code) do nothing;
